const ORDER_STATUSES = {
  PLACED: "PLACED",
  PACKED: "PACKED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
};

const STATUS_FLOW = [
  ORDER_STATUSES.PLACED,
  ORDER_STATUSES.PACKED,
  ORDER_STATUSES.SHIPPED,
  ORDER_STATUSES.DELIVERED,
];

module.exports = {
  ORDER_STATUSES,
  STATUS_FLOW,
};
